### ISSUE TITLE
Released version not working

### ISSUE THREAD

**Issue by helenocampos** [catarinacosta/macTool#2]
Hello!
I tried downloading the released version 1.0, but when I tried to execute it didn't work. I followed the instructions in the readme.

Steps to reproduce:
1. Download the released version 1.0.
2. Execute the downloaded jar. "java -jar macTool-1.0.jar PATH_TO_REPO"

The following error was returned:

> Exception in thread "main" java.lang.ClassNotFoundException: br.ufac.si.mactool.MACTool
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:468)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:59)

Maybe the jar was generated without the required dependencies.

**Comment by bruunotrindade** [comment]
Hello, Heleno!

I updated the released version 1.0 Jar file. Please, try again :)

Thanks for reporting!
